# Generated by Django 4.0.1 on 2022-01-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Profile Trash',
                'verbose_name_plural': 'Profiles Trash',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('profiles.profile',),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
